import React from 'react';
import { 
  Truck, LayoutDashboard, Package, Map, Users, AlertTriangle, 
  Settings, FileText, Bell, Search, Menu, X, Battery, 
  Thermometer, Navigation, Calendar, ShieldCheck, ChevronRight,
  TrendingUp, BarChart3, Radio, Fuel, Wrench, LogOut, Plus,
  MapPin, Clock, DollarSign, User, Shield, Lock, FileOutput,
  UploadCloud, Filter, CheckCircle, Star, Globe, Facebook, 
  Twitter, Linkedin, Instagram, ArrowRight, Play, Mail,
  Cloud, Sun, CloudRain, Wind, Activity, Layers, Target,
  Zap, AlertOctagon, MoreHorizontal
} from 'lucide-react';

export const Icons = {
  Truck,
  Dashboard: LayoutDashboard,
  Freight: Package,
  Package,
  Map,
  Drivers: Users,
  Alert: AlertTriangle,
  Settings,
  Reports: FileText,
  FileText,
  Bell,
  Search,
  Menu,
  Close: X,
  Battery,
  Temp: Thermometer,
  Nav: Navigation,
  Calendar,
  Compliance: ShieldCheck,
  ChevronRight,
  Trend: TrendingUp,
  Chart: BarChart3,
  Sensor: Radio,
  Fuel,
  Maintenance: Wrench,
  Wrench,
  Logout: LogOut,
  Plus,
  Pin: MapPin,
  MapPin,
  Clock,
  Cost: DollarSign,
  User,
  Security: Shield,
  Shield,
  Lock,
  IO: FileOutput,
  Upload: UploadCloud,
  Filter,
  Check: CheckCircle,
  Star,
  Globe,
  Facebook,
  Twitter,
  Linkedin,
  Instagram,
  ArrowRight,
  Play,
  Mail,
  Cloud,
  Sun,
  CloudRain,
  Wind,
  Activity,
  Layers,
  Target,
  Zap,
  AlertOctagon,
  More: MoreHorizontal
};